// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Book struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Author      string          `json:"author"`
	Description string          `json:"description"`
	Genres      json.RawMessage `json:"genres"`
	Language    string          `json:"language"`
	FileName    string          `json:"file_name"`
	Bookpath    string          `json:"bookpath"`
	Rating      sql.NullFloat64 `json:"rating"`
}
