// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Book struct {
	ID          int64
	Title       string
	Author      string
	Description string
	Genres      string
	Language    string
	FileName    string
	Bookpath    string
	Rating      sql.NullFloat64
}
